### ISSUE TITLE
`uline` package cannot be searched by keyword `uline`

### ISSUE THREAD

**Issue by TonalidadeHidrica** [matsud224/satyrographos-package-index-v2#11]
Simply strange.

![image](https://user-images.githubusercontent.com/47710717/118835627-2365a500-b8fe-11eb-97c3-7d05bbd31e16.png)

**Comment by matsud224** [comment]
This problem was fixed by replacing lunr with js-search (`js-search` branch).
Thank you for reporting an issue!

**Comment by TonalidadeHidrica** [comment]
It works!  Thanks a lot.
