### ISSUE TITLE
Search by command name

### ISSUE THREAD

**Issue by TonalidadeHidrica** [matsud224/satyrographos-package-index-v2#8]
It may be useful if we can search package by command name.  It would be fantastic if we can see the resulting appearance in the search result.  (For example, I wanted to search if any package has `\pdv` equivalent.)

**Comment by TonalidadeHidrica** [comment]
[In the future](https://github.com/gfngfn/SATySFi/wiki/%E8%BF%BD%E5%8A%A0%E3%81%97%E3%81%9F%E3%81%84%E6%A9%9F%E8%83%BD%E3%81%A8%E3%81%9D%E3%81%AE%E3%82%A4%E3%83%A1%E3%83%BC%E3%82%B8#2020-03-22-doc-comment) we may generate a document from a package.  Once the feature is released, we may obtain the list of functions defined in the package.  (Also, we will have another task to integrate docs with satyrographos package index website.)

**Comment by matsud224** [comment]
Thank you for sending an issue!
I implemented package searching by command name (related commit: 6c1a55301b38fcafdef3c64be5eaac802f9e5069, e3b101d13786703f7796a50bbc3eb5840177322d, b696e18711da0a4327d0e63e79622d100ebcaab9).

**Comment by TonalidadeHidrica** [comment]
Splendid!  I'd like to appreciate for your very early action.  There are still some room for improvement (e.g. showing the matched command name in the search result, or maybe in the future do the "correct" parsing of code), but current one is already sufficient.  So I think it's better to close the issue.  Again, thanks a lot!
